apiVersion: 1
datasources:
  - name: prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: 'http://prometheus:9090'
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: GET
      keepCookies: []
      tlsSkipVerify: true
    editable: true
  
