FROM python:3.7.4-alpine3.10
MAINTAINER hlafleur@touchtunes.com

COPY ./requirements.txt /requirements.txt
COPY ./scripts /scripts

RUN pip3 install --upgrade -r /requirements.txt

ENTRYPOINT ["/usr/bin/env", "python3", "/scripts/assemble_config.py"]
