---
global:
  resolve_timeout: 1h

route:
  group_by: [alertname]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: slack-meetup # default receiver for all unsorted notifications

receivers:
  - name: slack-meetup
    slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: meetup
        send_resolved: true
        text: "<!channel> {{ .CommonAnnotations.description }}"
